from django.conf.urls import patterns, url
from reportsViewer import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^archive/$', views.archive, name='archive'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/(?P<type>[\w]+)/$', views.category, name='category'),
        url(r'^category_realtime/(?P<category_name_slug>[\w\-]+)/$', views.category_realtime, name='category_realtime'),
        url(r'^category_archive/(?P<category_name_slug>[\w\-]+)/$', views.category_archive, name='category_archive'),
        url(r'^report/(?P<report_id>\d+)/$', views.report, name='report'),
        url(r'^report_realtime/(?P<report_id>\d+)/$', views.report_realtime, name='report_realtime'),
        url(r'^report_archive/(?P<report_id>\d+)/$', views.report_archive, name='report_archive'),
        url(r'^archive_report/(?P<report_id>\d+)/$', views.archive_report, name='archive_report'),
        url(r'^request_report/$', views.request_report, name='request_report'),
        url(r'^publish_report/$', views.publish_report, name='publish_report'),
        url(r'^publish_report_save/$', views.publish_report_save, name='publish_report_save'),
        url(r'^download_report/(?P<report_id>\d+)/$', views.download_report, name='download_report'),
        url(r'^download_report_archive/(?P<report_id>\d+)/$', views.download_report_archive, name='download_report_archive'),
        url(r'^delete_report/(?P<report_id>\d+)/$', views.delete_report, name='delete_report'),
        url(r'^delete_report_archive/(?P<report_id>\d+)/$', views.delete_report_archive, name='delete_report_archive'),
        url(r'^realtime_reports/$', views.realtime_reports, name='realtime_reports'),
        url(r'^generate_report/(?P<report_id>\d+)/$', views.generate_report, name='generate_report'),
        url(r'^login/', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        )
